### ISSUE TITLE
Can't activate plugin...

### ISSUE THREAD

**Issue by mandoerik** [squarou/pydio-mailer.phpmailer-smtp#1]
Hi! 
Thanks for making this plugin. When I try to enable the plugin in the plugins setting in pydio it says plugin successfully updated  but when I refresh the page the tickbox is back to disabled mode. And I don't get any smtp options under the section mailers in pydio. What am I doing wrong? I can't see that there are any problems with user rights...

/Erik

**Comment by squarou** [comment]
Hi Erik, I'm not sure to understand where the problem is.
I describe the procedure to install the plugin, just tell me where is the problem :

1. once the mugin is uploaded, activate it in Settings > Plugins > Send Mail
2. clear the cache form the Plugins page
3. go to Settings > Send Mail (http://yourdomain/pydio/settings/parameters/core.mailer)
4. select PHPMailer-smtp and fill the server's settings and credentials
5. then save
6. go to Settings and clear the cache again
7. check if it works (mail sent and received)

**Comment by zx81sp** [comment]
Same problem here with 8.0.2, when you try to activate the plugin (step 1) seems that it's done but when you reload the page, the plugin is disabled.

Edit: stupid problem...seems a file permissions issue, the XML can't be writed so it allways stay in "disable" mode, changed permissions and all works fine.

Thanks

**Comment by squarou** [comment]
seems a file permissions issue, the XML can't be writed so it allways stay in "disable" mode
